function removeFields(obj) {
  let FIELDS_TO_REMOVE = new Set(['allowCopy', 'createdAt', 'createdBy', 'isAddable', 'isAddableExisting', 'isRemovable', 'maxLines', 'minLines', 'modifiedAt', 'modifiedBy', 'renderAsSingleSection', 'repeatable', 'visibleApprover', 'visibleRequestor', 'controlType', 'controlTypeGroup', 'defaultValue', 'dynamicDefault', 'editableApprover', 'editableExisting', 'editableExistingApprover', 'editableExistingRequestor', 'editableRequester', 'hasInformation', 'mandatory', 'sample', 'showOnTableColumn', 'isKeepValue'])

  if (Array.isArray(obj)) {
    return obj.map(removeFields)
  }

  if (obj !== null && typeof obj === 'object') {
    return Object.fromEntries(
      Object.entries(obj)
        .filter(([key]) => !FIELDS_TO_REMOVE.has(key))
        .map(([key, value]) => [key, removeFields(value)]),
    )
  }

  return obj
}

const originalData = {
  allowCopy: true,
  businessTable: 'prd.model.final.Product',
  createdAt: '2026-02-25T10:10:40.910Z',
  createdBy: 'multiple.demo@laidon.com',
  isAddable: true,
  isAddableExisting: true,
  isRemovable: true,
  maxLines: null,
  minLines: null,
  modifiedAt: '2026-02-25T10:10:40.910Z',
  modifiedBy: 'multiple.demo@laidon.com',
  parentSectionID: '',
  renderAsSingleSection: false,
  repeatable: false,
  sectionID: 'ROOT',
  sectionIndex: 0,
  sectionName: 'Root',
  tempID: '2W_SM_MM01',
  visibleApprover: true,
  visibleRequestor: true,
  values: [
    {
      actions: {
        MDGInsertionFlag: 'ACTIVE',
        MDGDeletionFlag: '',
        MDGExistingFlag: false,
      },
      sections: [
        {
          allowCopy: true,
          businessTable: 'prd.model.final.ProductMapping',
          createdAt: '2026-02-25T10:10:40.910Z',
          createdBy: 'multiple.demo@laidon.com',
          isAddable: true,
          isAddableExisting: true,
          isRemovable: true,
          maxLines: null,
          minLines: null,
          modifiedAt: '2026-02-25T10:10:40.910Z',
          modifiedBy: 'multiple.demo@laidon.com',
          parentSectionID: 'ROOT',
          renderAsSingleSection: false,
          repeatable: true,
          sectionID: 'TARGETSYSTEM',
          sectionIndex: 0,
          sectionName: 'Target System',
          tempID: '2W_SM_MM01',
          visibleApprover: true,
          visibleRequestor: true,
          values: [
            {
              actions: {
                MDGInsertionFlag: 'ACTIVE',
                MDGDeletionFlag: '',
                MDGExistingFlag: false,
              },
              sections: [],
              fields: [
                {
                  allowCopy: true,
                  businessField: 'ERPSystem',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '1.0',
                  fieldLabel: 'ERPSystem',
                  fieldName: 'ERPSystem',
                  hasInformation: false,
                  keyField: false,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'ERPSystem',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"targetSystem ne \'CENTRAL\'","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  value: 'S4',
                  additionalProps: {
                    visible: null,
                    path: 'values/0/sections/0/values/0/fields/0/',
                    isKeepValue: true,
                  },
                },
                {
                  allowCopy: false,
                  businessField: 'ERPproduct',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'INPUT',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: false,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: false,
                  fieldIndex: '2.0',
                  fieldLabel: 'ERPproduct',
                  fieldName: 'ERPproduct',
                  hasInformation: false,
                  keyField: false,
                  mandatory: false,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'ERP Material Number',
                  showOnTableColumn: true,
                  sourceData: '',
                  sourceType: '',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: false,
                  value: null,
                  additionalProps: {
                    visible: null,
                    path: 'values/0/sections/0/values/0/fields/1/',
                  },
                },
                {
                  allowCopy: false,
                  businessField: 'product',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'INPUT',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: false,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: false,
                  fieldIndex: '3.0',
                  fieldLabel: 'product',
                  fieldName: 'product',
                  hasInformation: false,
                  keyField: false,
                  mandatory: false,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'SMDG Material Number',
                  showOnTableColumn: true,
                  sourceData: '',
                  sourceType: '',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  value: null,
                  additionalProps: {
                    visible: null,
                    path: 'values/0/sections/0/values/0/fields/2/',
                    isKeepValue: true,
                  },
                },
              ],
              isRuleGenerated: true,
              indicator: 1,
            },
            {
              actions: {
                MDGInsertionFlag: 'ACTIVE',
                MDGDeletionFlag: '',
                MDGExistingFlag: false,
              },
              sections: [],
              fields: [
                {
                  allowCopy: true,
                  businessField: 'ERPSystem',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '1.0',
                  fieldLabel: 'ERPSystem',
                  fieldName: 'ERPSystem',
                  hasInformation: false,
                  keyField: false,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'ERPSystem',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"targetSystem ne \'CENTRAL\'","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  value: 'ECC',
                  additionalProps: {
                    visible: null,
                    path: 'values/0/sections/0/values/1/fields/0/',
                    isKeepValue: true,
                  },
                },
                {
                  allowCopy: false,
                  businessField: 'ERPproduct',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'INPUT',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: false,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: false,
                  fieldIndex: '2.0',
                  fieldLabel: 'ERPproduct',
                  fieldName: 'ERPproduct',
                  hasInformation: false,
                  keyField: false,
                  mandatory: false,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'ERP Material Number',
                  showOnTableColumn: true,
                  sourceData: '',
                  sourceType: '',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: false,
                  value: null,
                  additionalProps: {
                    visible: null,
                    path: 'values/0/sections/0/values/1/fields/1/',
                  },
                },
                {
                  allowCopy: false,
                  businessField: 'product',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'INPUT',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: false,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: false,
                  fieldIndex: '3.0',
                  fieldLabel: 'product',
                  fieldName: 'product',
                  hasInformation: false,
                  keyField: false,
                  mandatory: false,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'SMDG Material Number',
                  showOnTableColumn: true,
                  sourceData: '',
                  sourceType: '',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  value: null,
                  additionalProps: {
                    visible: null,
                    path: 'values/0/sections/0/values/1/fields/2/',
                    isKeepValue: true,
                  },
                },
              ],
              isRuleGenerated: true,
              indicator: 2,
            },
            {
              actions: {
                MDGInsertionFlag: 'ACTIVE',
                MDGDeletionFlag: '',
                MDGExistingFlag: false,
              },
              sections: [],
              fields: [
                {
                  allowCopy: true,
                  businessField: 'ERPSystem',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '1.0',
                  fieldLabel: 'ERPSystem',
                  fieldName: 'ERPSystem',
                  hasInformation: false,
                  keyField: false,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'ERPSystem',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"targetSystem ne \'CENTRAL\'","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  additionalProps: {
                    visible: null,
                    path: 'fields/0/',
                    isKeepValue: true,
                    selectedMDData: {
                      description: 'WWWW2',
                      isActive: true,
                      targetSystem: 'WIL2',
                    },
                  },
                  value: 'WIL2',
                  hiddenControlId: '__input5',
                  controlId: '__input4',
                  keyFieldValue: 'WIL2',
                  valueState: 'None',
                  valueStateText: '',
                },
                {
                  allowCopy: false,
                  businessField: 'ERPproduct',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'INPUT',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: false,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: false,
                  fieldIndex: '2.0',
                  fieldLabel: 'ERPproduct',
                  fieldName: 'ERPproduct',
                  hasInformation: false,
                  keyField: false,
                  mandatory: false,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'ERP Material Number',
                  showOnTableColumn: true,
                  sourceData: '',
                  sourceType: '',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: false,
                  additionalProps: {
                    visible: null,
                    path: 'fields/1/',
                  },
                  value: null,
                  controlId: '__input6',
                  valueState: 'None',
                  valueStateText: '',
                },
                {
                  allowCopy: false,
                  businessField: 'product',
                  businessTable: 'prd.model.final.ProductMapping',
                  controlType: 'INPUT',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: false,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: false,
                  fieldIndex: '3.0',
                  fieldLabel: 'product',
                  fieldName: 'product',
                  hasInformation: false,
                  keyField: false,
                  mandatory: false,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'TARGETSYSTEM',
                  shortFieldLabel: 'SMDG Material Number',
                  showOnTableColumn: true,
                  sourceData: '',
                  sourceType: '',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  additionalProps: {
                    visible: null,
                    path: 'fields/2/',
                    isKeepValue: true,
                  },
                  value: null,
                  controlId: '__input7',
                  valueState: 'None',
                  valueStateText: '',
                },
              ],
              canBeApproved: true,
            },
          ],
          additionalProps: {
            visible: null,
            path: 'values/0/sections/0/',
          },
        },
        {
          allowCopy: true,
          businessTable: 'prd.model.final.Product',
          createdAt: '2026-02-25T10:10:40.910Z',
          createdBy: 'multiple.demo@laidon.com',
          isAddable: true,
          isAddableExisting: true,
          isRemovable: true,
          maxLines: null,
          minLines: null,
          modifiedAt: '2026-02-25T10:10:40.910Z',
          modifiedBy: 'multiple.demo@laidon.com',
          parentSectionID: 'ROOT',
          renderAsSingleSection: false,
          repeatable: false,
          sectionID: 'GENERAL',
          sectionIndex: 1,
          sectionName: 'General Data',
          tempID: '2W_SM_MM01',
          visibleApprover: true,
          visibleRequestor: true,
          values: [
            {
              actions: {
                MDGInsertionFlag: 'ACTIVE',
                MDGDeletionFlag: '',
                MDGExistingFlag: false,
              },
              sections: [
                {
                  allowCopy: true,
                  businessTable: 'prd.model.final.Product',
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  isAddable: true,
                  isAddableExisting: true,
                  isRemovable: true,
                  maxLines: null,
                  minLines: null,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  parentSectionID: 'GENERAL',
                  renderAsSingleSection: false,
                  repeatable: false,
                  sectionID: 'BASIC',
                  sectionIndex: 0,
                  sectionName: 'Basic Data',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  values: [
                    {
                      actions: {
                        MDGInsertionFlag: 'ACTIVE',
                        MDGDeletionFlag: '',
                        MDGExistingFlag: false,
                      },
                      sections: [],
                      fields: [
                        {
                          allowCopy: false,
                          businessField: 'product',
                          businessTable: 'prd.model.final.Product',
                          controlType: 'INPUT',
                          controlTypeGroup: null,
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          defaultValue: null,
                          dynamicDefault: null,
                          editableApprover: false,
                          editableExisting: false,
                          editableExistingApprover: false,
                          editableExistingRequestor: false,
                          editableRequester: false,
                          fieldIndex: '1.0',
                          fieldLabel: 'product',
                          fieldName: 'product',
                          hasInformation: false,
                          keyField: false,
                          mandatory: false,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sample: null,
                          sectionID: 'BASIC',
                          shortFieldLabel: 'Product',
                          showOnTableColumn: true,
                          sourceData: '',
                          sourceType: '',
                          tempID: '2W_SM_MM01',
                          visibleApprover: true,
                          visibleRequestor: true,
                          isKeepValue: true,
                          value: null,
                          additionalProps: {
                            visible: null,
                            path: 'values/0/sections/1/values/0/sections/0/values/0/fields/0/',
                            isKeepValue: true,
                          },
                          controlId: '__input1',
                        },
                      ],
                    },
                  ],
                  additionalProps: {
                    visible: null,
                    path: 'values/0/sections/1/values/0/sections/0/',
                  },
                },
              ],
              fields: [],
            },
          ],
          additionalProps: {
            visible: null,
            path: 'values/0/sections/1/',
          },
        },
        {
          allowCopy: true,
          businessTable: 'prd.model.final.ProductPlant',
          createdAt: '2026-02-25T10:10:40.910Z',
          createdBy: 'multiple.demo@laidon.com',
          isAddable: true,
          isAddableExisting: true,
          isRemovable: true,
          maxLines: null,
          minLines: null,
          modifiedAt: '2026-02-25T10:10:40.910Z',
          modifiedBy: 'multiple.demo@laidon.com',
          parentSectionID: 'ROOT',
          renderAsSingleSection: false,
          repeatable: true,
          sectionID: 'PLANTDATA',
          sectionIndex: 2,
          sectionName: 'Plant Data',
          tempID: '2W_SM_MM01',
          visibleApprover: true,
          visibleRequestor: true,
          values: [
            {
              actions: {
                MDGInsertionFlag: 'ACTIVE',
                MDGDeletionFlag: '',
                MDGExistingFlag: false,
              },
              sections: [
                {
                  allowCopy: true,
                  businessTable: 'prd.model.final.ProductPlantMapping',
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  isAddable: true,
                  isAddableExisting: true,
                  isRemovable: true,
                  maxLines: null,
                  minLines: null,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  parentSectionID: 'PLANTDATA',
                  renderAsSingleSection: false,
                  repeatable: true,
                  sectionID: 'PLANTDATAMAPPING',
                  sectionIndex: 0,
                  sectionName: 'Plant Local Data',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  values: [],
                  additionalProps: {
                    visible: null,
                    path: 'sections/0/',
                  },
                },
                {
                  allowCopy: true,
                  businessTable: 'prd.model.final.ProductStorageLocation',
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  isAddable: true,
                  isAddableExisting: true,
                  isRemovable: true,
                  maxLines: null,
                  minLines: null,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  parentSectionID: 'PLANTDATA',
                  renderAsSingleSection: false,
                  repeatable: true,
                  sectionID: 'STORAGELOCATION',
                  sectionIndex: 1,
                  sectionName: 'Storage Location',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  values: [
                    {
                      actions: {
                        MDGInsertionFlag: 'ACTIVE',
                        MDGDeletionFlag: '',
                        MDGExistingFlag: false,
                      },
                      sections: [],
                      fields: [
                        {
                          allowCopy: true,
                          businessField: 'targetSystemProductStorageLocation',
                          businessTable: 'prd.model.final.ProductStorageLocation',
                          controlType: 'F4',
                          controlTypeGroup: null,
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          defaultValue: null,
                          dynamicDefault: null,
                          editableApprover: true,
                          editableExisting: false,
                          editableExistingApprover: false,
                          editableExistingRequestor: false,
                          editableRequester: true,
                          fieldIndex: '1.0',
                          fieldLabel: 'targetSystemProductStorageLocation',
                          fieldName: 'targetSystemProductStorageLocation',
                          hasInformation: false,
                          keyField: false,
                          mandatory: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sample: null,
                          sectionID: 'STORAGELOCATION',
                          shortFieldLabel: 'Target System Product Storage Location',
                          showOnTableColumn: true,
                          sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                          sourceType: 'CUSTOMVIEW',
                          tempID: '2W_SM_MM01',
                          visibleApprover: true,
                          visibleRequestor: true,
                          isKeepValue: true,
                          additionalProps: {
                            visible: null,
                            path: 'fields/0/',
                            isKeepValue: true,
                            selectedMDData: {
                              description: 'S4 System',
                              isActive: true,
                              targetSystem: 'S4',
                            },
                          },
                          value: 'S4',
                          hiddenControlId: '__input13',
                          controlId: '__input12',
                          keyFieldValue: 'S4',
                          valueState: 'None',
                          valueStateText: '',
                        },
                        {
                          allowCopy: true,
                          businessField: 'storageLocation',
                          businessTable: 'prd.model.final.ProductStorageLocation',
                          controlType: 'F4',
                          controlTypeGroup: null,
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          defaultValue: null,
                          dynamicDefault: null,
                          editableApprover: true,
                          editableExisting: false,
                          editableExistingApprover: false,
                          editableExistingRequestor: false,
                          editableRequester: true,
                          fieldIndex: '2.0',
                          fieldLabel: 'storageLocation',
                          fieldName: 'storageLocation',
                          hasInformation: false,
                          keyField: false,
                          mandatory: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sample: null,
                          sectionID: 'STORAGELOCATION',
                          shortFieldLabel: 'Storage Location',
                          showOnTableColumn: true,
                          sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["storageLocation","description"],"entity":"UIMDStorageLocation","fields":["plant","storageLocation","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"storageLocation","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                          sourceType: 'CUSTOMVIEW',
                          tempID: '2W_SM_MM01',
                          visibleApprover: true,
                          visibleRequestor: true,
                          isKeepValue: true,
                          additionalProps: {
                            visible: null,
                            path: 'fields/1/',
                            targetRule: {
                              configRules: [
                                {
                                  configType: 'FILTER',
                                  configValue: 'plant',
                                  createdAt: '2026-02-25T10:10:40.910Z',
                                  createdBy: 'multiple.demo@laidon.com',
                                  isEnable: true,
                                  modifiedAt: '2026-02-25T10:10:40.910Z',
                                  modifiedBy: 'multiple.demo@laidon.com',
                                  sliceFrom: null,
                                  sliceLength: null,
                                  sourceField: 'plant',
                                  sourceSectionID: 'PLANTDATA',
                                  targetField: 'storageLocation',
                                  targetSectionID: 'STORAGELOCATION',
                                  tempID: '2W_SM_MM01',
                                },
                              ],
                              derivationRules: [],
                            },
                            isKeepValue: true,
                            selectedMDData: {
                              description: 'Lagerort 0001',
                              isActive: true,
                              plant: '0001',
                              storageLocation: '0001',
                            },
                          },
                          value: '0001',
                          hiddenControlId: '__input15',
                          controlId: '__input14',
                          keyFieldValue: '0001',
                          valueState: 'None',
                          valueStateText: '',
                        },
                      ],
                      canBeApproved: true,
                    },
                  ],
                  additionalProps: {
                    visible: null,
                    path: 'sections/1/',
                  },
                },
              ],
              fields: [
                {
                  allowCopy: true,
                  businessField: 'targetSystemProductPlant',
                  businessTable: 'prd.model.final.ProductPlant',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '1.0',
                  fieldLabel: 'targetSystemProductPlant',
                  fieldName: 'targetSystemProductPlant',
                  hasInformation: false,
                  keyField: false,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'PLANTDATA',
                  shortFieldLabel: 'Target System Product Plant',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  additionalProps: {
                    visible: null,
                    path: 'fields/0/',
                    isKeepValue: true,
                    selectedMDData: {
                      description: 'S4 System',
                      isActive: true,
                      targetSystem: 'S4',
                    },
                  },
                  value: 'S4',
                  hiddenControlId: '__input9',
                  controlId: '__input8',
                  keyFieldValue: 'S4',
                  valueState: 'None',
                  valueStateText: '',
                },
                {
                  allowCopy: true,
                  businessField: 'plant',
                  businessTable: 'prd.model.final.ProductPlant',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '2.0',
                  fieldLabel: 'plant',
                  fieldName: 'plant',
                  hasInformation: false,
                  keyField: true,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'PLANTDATA',
                  shortFieldLabel: 'Plant',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["plantID"],"entity":"UIMDPlant","fields":["plantID","purchasingOrg","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"plantID","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  additionalProps: {
                    visible: null,
                    path: 'fields/1/',
                    sourceRule: {
                      configRules: [
                        {
                          configType: 'FILTER',
                          configValue: 'plant',
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sliceFrom: null,
                          sliceLength: null,
                          sourceField: 'plant',
                          sourceSectionID: 'PLANTDATA',
                          targetField: 'mrpResponsible',
                          targetSectionID: 'MRP1',
                          tempID: '2W_SM_MM01',
                        },
                        {
                          configType: 'FILTER',
                          configValue: 'plant',
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sliceFrom: null,
                          sliceLength: null,
                          sourceField: 'plant',
                          sourceSectionID: 'PLANTDATA',
                          targetField: 'storageLocation',
                          targetSectionID: 'STORAGELOCATION',
                          tempID: '2W_SM_MM01',
                        },
                      ],
                      derivationRules: [
                        {
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          ruleID: 'PRD_PRD_PLANT',
                          tempID: '2W_SM_MM01',
                          derivationRules: [
                            {
                              businessField: 'plant',
                              businessTable: 'ProductPlant',
                              configType: 'Source',
                              configValue: '0001',
                              createdAt: '2024-10-08T07:35:56.242Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: 'EQUAL',
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpType',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: 'ND',
                              createdAt: '2024-10-08T07:52:27.523Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'replacementPart',
                              businessTable: 'ProductPlant',
                              configType: 'Target',
                              configValue: 'A',
                              createdAt: '2024-10-08T08:05:51.935Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpResponsible',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: '0001-001',
                              createdAt: '2024-10-08T07:53:47.425Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpGroup',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: '0001-0000',
                              createdAt: '2024-10-08T08:18:23.785Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpType',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: 'PD',
                              createdAt: '2024-10-08T08:17:26.594Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'lotSizingProcedure',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: 'PK',
                              createdAt: '2024-10-08T07:47:01.395Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'lotSizingProcedure',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: 'EX',
                              createdAt: '2024-10-08T08:19:16.017Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'inHouseProductionTime',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: '5',
                              createdAt: '2024-10-08T07:45:27.389Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                          ],
                          options: {
                            singleSource: false,
                            repeatableSourceTargetLine: [0],
                          },
                        },
                      ],
                    },
                    isKeepValue: true,
                    selectedMDData: {
                      description: 'Europe',
                      isActive: true,
                      plantID: '0001',
                      purchasingOrg: '',
                    },
                  },
                  value: '0001',
                  hiddenControlId: '__input11',
                  controlId: '__input10',
                  keyFieldValue: '0001',
                  valueState: 'None',
                  valueStateText: '',
                },
              ],
              canBeApproved: true,
            },
            {
              actions: {
                MDGInsertionFlag: 'ACTIVE',
                MDGDeletionFlag: '',
                MDGExistingFlag: false,
              },
              sections: [
                {
                  allowCopy: true,
                  businessTable: 'prd.model.final.ProductPlantMapping',
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  isAddable: true,
                  isAddableExisting: true,
                  isRemovable: true,
                  maxLines: null,
                  minLines: null,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  parentSectionID: 'PLANTDATA',
                  renderAsSingleSection: false,
                  repeatable: true,
                  sectionID: 'PLANTDATAMAPPING',
                  sectionIndex: 0,
                  sectionName: 'Plant Local Data',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  values: [
                    {
                      actions: {
                        MDGInsertionFlag: 'ACTIVE',
                        MDGDeletionFlag: '',
                        MDGExistingFlag: false,
                      },
                      sections: [],
                      fields: [
                        {
                          allowCopy: true,
                          businessField: 'ERPSystem',
                          businessTable: 'prd.model.final.ProductPlantMapping',
                          controlType: 'F4',
                          controlTypeGroup: null,
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          defaultValue: '',
                          dynamicDefault: null,
                          editableApprover: true,
                          editableExisting: false,
                          editableExistingApprover: false,
                          editableExistingRequestor: false,
                          editableRequester: true,
                          fieldIndex: '1.0',
                          fieldLabel: 'ERPSystem',
                          fieldName: 'ERPSystem',
                          hasInformation: false,
                          keyField: false,
                          mandatory: false,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sample: null,
                          sectionID: 'PLANTDATAMAPPING',
                          shortFieldLabel: 'ERPSystem',
                          showOnTableColumn: true,
                          sourceData: '{"additionalFilter":"targetSystem ne \'CENTRAL\'","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                          sourceType: 'CUSTOMVIEW',
                          tempID: '2W_SM_MM01',
                          visibleApprover: true,
                          visibleRequestor: true,
                          isKeepValue: true,
                          additionalProps: {
                            visible: null,
                            path: 'fields/0/',
                            isKeepValue: true,
                            selectedMDData: {
                              description: 'ECC System',
                              isActive: true,
                              targetSystem: 'ECC',
                            },
                          },
                          value: 'ECC',
                          hiddenControlId: '__input21',
                          controlId: '__input20',
                          keyFieldValue: 'ECC',
                          valueState: 'None',
                          valueStateText: '',
                        },
                        {
                          allowCopy: true,
                          businessField: 'ERPpurchasingGroup',
                          businessTable: 'prd.model.final.ProductPlantMapping',
                          controlType: 'F4',
                          controlTypeGroup: null,
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          defaultValue: '',
                          dynamicDefault: null,
                          editableApprover: true,
                          editableExisting: false,
                          editableExistingApprover: false,
                          editableExistingRequestor: false,
                          editableRequester: true,
                          fieldIndex: '2.0',
                          fieldLabel: 'ERPpurchasingGroup',
                          fieldName: 'ERPpurchasingGroup',
                          hasInformation: false,
                          keyField: false,
                          mandatory: false,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sample: null,
                          sectionID: 'PLANTDATAMAPPING',
                          shortFieldLabel: 'Purchasing Group',
                          showOnTableColumn: true,
                          sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["purchasingGroup","description"],"entity":"UIMDPurchasingGroup","fields":["purchasingGroup","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"purchasingGroup","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                          sourceType: 'CUSTOMVIEW',
                          tempID: '2W_SM_MM01',
                          visibleApprover: true,
                          visibleRequestor: true,
                          isKeepValue: false,
                          additionalProps: {
                            visible: null,
                            path: 'fields/1/',
                            selectedMDData: {
                              description: 'Chef,H.',
                              isActive: true,
                              purchasingGroup: '000',
                            },
                          },
                          value: '000',
                          hiddenControlId: '__input23',
                          controlId: '__input22',
                          keyFieldValue: '000',
                          valueState: 'None',
                          valueStateText: '',
                        },
                      ],
                      canBeApproved: true,
                    },
                  ],
                  additionalProps: {
                    visible: null,
                    path: 'sections/0/',
                  },
                },
                {
                  allowCopy: true,
                  businessTable: 'prd.model.final.ProductStorageLocation',
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  isAddable: true,
                  isAddableExisting: true,
                  isRemovable: true,
                  maxLines: null,
                  minLines: null,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  parentSectionID: 'PLANTDATA',
                  renderAsSingleSection: false,
                  repeatable: true,
                  sectionID: 'STORAGELOCATION',
                  sectionIndex: 1,
                  sectionName: 'Storage Location',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  values: [
                    {
                      actions: {
                        MDGInsertionFlag: 'ACTIVE',
                        MDGDeletionFlag: '',
                        MDGExistingFlag: false,
                      },
                      sections: [],
                      fields: [
                        {
                          allowCopy: true,
                          businessField: 'targetSystemProductStorageLocation',
                          businessTable: 'prd.model.final.ProductStorageLocation',
                          controlType: 'F4',
                          controlTypeGroup: null,
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          defaultValue: null,
                          dynamicDefault: null,
                          editableApprover: true,
                          editableExisting: false,
                          editableExistingApprover: false,
                          editableExistingRequestor: false,
                          editableRequester: true,
                          fieldIndex: '1.0',
                          fieldLabel: 'targetSystemProductStorageLocation',
                          fieldName: 'targetSystemProductStorageLocation',
                          hasInformation: false,
                          keyField: false,
                          mandatory: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sample: null,
                          sectionID: 'STORAGELOCATION',
                          shortFieldLabel: 'Target System Product Storage Location',
                          showOnTableColumn: true,
                          sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                          sourceType: 'CUSTOMVIEW',
                          tempID: '2W_SM_MM01',
                          visibleApprover: true,
                          visibleRequestor: true,
                          isKeepValue: true,
                          additionalProps: {
                            visible: null,
                            path: 'fields/0/',
                            isKeepValue: true,
                            selectedMDData: {
                              description: 'S4 System',
                              isActive: true,
                              targetSystem: 'S4',
                            },
                          },
                          value: 'S4',
                          hiddenControlId: '__input25',
                          controlId: '__input24',
                          keyFieldValue: 'S4',
                          valueState: 'None',
                          valueStateText: '',
                        },
                        {
                          allowCopy: true,
                          businessField: 'storageLocation',
                          businessTable: 'prd.model.final.ProductStorageLocation',
                          controlType: 'F4',
                          controlTypeGroup: null,
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          defaultValue: null,
                          dynamicDefault: null,
                          editableApprover: true,
                          editableExisting: false,
                          editableExistingApprover: false,
                          editableExistingRequestor: false,
                          editableRequester: true,
                          fieldIndex: '2.0',
                          fieldLabel: 'storageLocation',
                          fieldName: 'storageLocation',
                          hasInformation: false,
                          keyField: false,
                          mandatory: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sample: null,
                          sectionID: 'STORAGELOCATION',
                          shortFieldLabel: 'Storage Location',
                          showOnTableColumn: true,
                          sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["storageLocation","description"],"entity":"UIMDStorageLocation","fields":["plant","storageLocation","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"storageLocation","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                          sourceType: 'CUSTOMVIEW',
                          tempID: '2W_SM_MM01',
                          visibleApprover: true,
                          visibleRequestor: true,
                          isKeepValue: true,
                          additionalProps: {
                            visible: null,
                            path: 'fields/1/',
                            targetRule: {
                              configRules: [
                                {
                                  configType: 'FILTER',
                                  configValue: 'plant',
                                  createdAt: '2026-02-25T10:10:40.910Z',
                                  createdBy: 'multiple.demo@laidon.com',
                                  isEnable: true,
                                  modifiedAt: '2026-02-25T10:10:40.910Z',
                                  modifiedBy: 'multiple.demo@laidon.com',
                                  sliceFrom: null,
                                  sliceLength: null,
                                  sourceField: 'plant',
                                  sourceSectionID: 'PLANTDATA',
                                  targetField: 'storageLocation',
                                  targetSectionID: 'STORAGELOCATION',
                                  tempID: '2W_SM_MM01',
                                },
                              ],
                              derivationRules: [],
                            },
                            isKeepValue: true,
                            selectedMDData: {
                              description: 'Lager 0002',
                              isActive: true,
                              plant: '0002',
                              storageLocation: '0002',
                            },
                          },
                          value: '0002',
                          hiddenControlId: '__input27',
                          controlId: '__input26',
                          keyFieldValue: '0002',
                          valueState: 'None',
                          valueStateText: '',
                        },
                      ],
                      canBeApproved: true,
                    },
                  ],
                  additionalProps: {
                    visible: null,
                    path: 'sections/1/',
                  },
                },
              ],
              fields: [
                {
                  allowCopy: true,
                  businessField: 'targetSystemProductPlant',
                  businessTable: 'prd.model.final.ProductPlant',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '1.0',
                  fieldLabel: 'targetSystemProductPlant',
                  fieldName: 'targetSystemProductPlant',
                  hasInformation: false,
                  keyField: false,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'PLANTDATA',
                  shortFieldLabel: 'Target System Product Plant',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  additionalProps: {
                    visible: null,
                    path: 'fields/0/',
                    isKeepValue: true,
                    selectedMDData: {
                      description: 'CENTRAL',
                      isActive: true,
                      targetSystem: 'CENTRAL',
                    },
                  },
                  value: 'CENTRAL',
                  hiddenControlId: '__input17',
                  controlId: '__input16',
                  keyFieldValue: 'CENTRAL',
                  valueState: 'None',
                  valueStateText: '',
                },
                {
                  allowCopy: true,
                  businessField: 'plant',
                  businessTable: 'prd.model.final.ProductPlant',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '2.0',
                  fieldLabel: 'plant',
                  fieldName: 'plant',
                  hasInformation: false,
                  keyField: true,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'PLANTDATA',
                  shortFieldLabel: 'Plant',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["plantID"],"entity":"UIMDPlant","fields":["plantID","purchasingOrg","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"plantID","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  additionalProps: {
                    visible: null,
                    path: 'fields/1/',
                    sourceRule: {
                      configRules: [
                        {
                          configType: 'FILTER',
                          configValue: 'plant',
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sliceFrom: null,
                          sliceLength: null,
                          sourceField: 'plant',
                          sourceSectionID: 'PLANTDATA',
                          targetField: 'mrpResponsible',
                          targetSectionID: 'MRP1',
                          tempID: '2W_SM_MM01',
                        },
                        {
                          configType: 'FILTER',
                          configValue: 'plant',
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sliceFrom: null,
                          sliceLength: null,
                          sourceField: 'plant',
                          sourceSectionID: 'PLANTDATA',
                          targetField: 'storageLocation',
                          targetSectionID: 'STORAGELOCATION',
                          tempID: '2W_SM_MM01',
                        },
                      ],
                      derivationRules: [
                        {
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          ruleID: 'PRD_PRD_PLANT',
                          tempID: '2W_SM_MM01',
                          derivationRules: [
                            {
                              businessField: 'plant',
                              businessTable: 'ProductPlant',
                              configType: 'Source',
                              configValue: '0001',
                              createdAt: '2024-10-08T07:35:56.242Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: 'EQUAL',
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpType',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: 'ND',
                              createdAt: '2024-10-08T07:52:27.523Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'replacementPart',
                              businessTable: 'ProductPlant',
                              configType: 'Target',
                              configValue: 'A',
                              createdAt: '2024-10-08T08:05:51.935Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpResponsible',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: '0001-001',
                              createdAt: '2024-10-08T07:53:47.425Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpGroup',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: '0001-0000',
                              createdAt: '2024-10-08T08:18:23.785Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpType',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: 'PD',
                              createdAt: '2024-10-08T08:17:26.594Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'lotSizingProcedure',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: 'PK',
                              createdAt: '2024-10-08T07:47:01.395Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'lotSizingProcedure',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: 'EX',
                              createdAt: '2024-10-08T08:19:16.017Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'inHouseProductionTime',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: '5',
                              createdAt: '2024-10-08T07:45:27.389Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                          ],
                          options: {
                            singleSource: false,
                            repeatableSourceTargetLine: [0],
                          },
                        },
                      ],
                    },
                    isKeepValue: true,
                    selectedMDData: {
                      description: 'Paris',
                      isActive: true,
                      plantID: '0002',
                      purchasingOrg: '',
                    },
                  },
                  value: '0002',
                  hiddenControlId: '__input19',
                  controlId: '__input18',
                  keyFieldValue: '0002',
                  valueState: 'None',
                  valueStateText: '',
                },
              ],
              canBeApproved: true,
            },
            {
              actions: {
                MDGInsertionFlag: 'ACTIVE',
                MDGDeletionFlag: '',
                MDGExistingFlag: false,
              },
              sections: [
                {
                  allowCopy: true,
                  businessTable: 'prd.model.final.ProductPlantMapping',
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  isAddable: true,
                  isAddableExisting: true,
                  isRemovable: true,
                  maxLines: null,
                  minLines: null,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  parentSectionID: 'PLANTDATA',
                  renderAsSingleSection: false,
                  repeatable: true,
                  sectionID: 'PLANTDATAMAPPING',
                  sectionIndex: 0,
                  sectionName: 'Plant Local Data',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  values: [],
                  additionalProps: {
                    visible: null,
                    path: 'sections/0/',
                  },
                },
                {
                  allowCopy: true,
                  businessTable: 'prd.model.final.ProductStorageLocation',
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  isAddable: true,
                  isAddableExisting: true,
                  isRemovable: true,
                  maxLines: null,
                  minLines: null,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  parentSectionID: 'PLANTDATA',
                  renderAsSingleSection: false,
                  repeatable: true,
                  sectionID: 'STORAGELOCATION',
                  sectionIndex: 1,
                  sectionName: 'Storage Location',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  values: [],
                  additionalProps: {
                    visible: null,
                    path: 'sections/1/',
                  },
                },
              ],
              fields: [
                {
                  allowCopy: true,
                  businessField: 'targetSystemProductPlant',
                  businessTable: 'prd.model.final.ProductPlant',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '1.0',
                  fieldLabel: 'targetSystemProductPlant',
                  fieldName: 'targetSystemProductPlant',
                  hasInformation: false,
                  keyField: false,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'PLANTDATA',
                  shortFieldLabel: 'Target System Product Plant',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["targetSystem"],"entity":"UIMDTargetSystem","fields":["targetSystem","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"targetSystem","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  additionalProps: {
                    visible: null,
                    path: 'fields/0/',
                    isKeepValue: true,
                    selectedMDData: {
                      description: 'WWWW2',
                      isActive: true,
                      targetSystem: 'WIL2',
                    },
                  },
                  value: 'WIL2',
                  hiddenControlId: '__input29',
                  controlId: '__input28',
                  keyFieldValue: 'WIL2',
                  valueState: 'None',
                  valueStateText: '',
                },
                {
                  allowCopy: true,
                  businessField: 'plant',
                  businessTable: 'prd.model.final.ProductPlant',
                  controlType: 'F4',
                  controlTypeGroup: null,
                  createdAt: '2026-02-25T10:10:40.910Z',
                  createdBy: 'multiple.demo@laidon.com',
                  defaultValue: null,
                  dynamicDefault: null,
                  editableApprover: true,
                  editableExisting: false,
                  editableExistingApprover: false,
                  editableExistingRequestor: false,
                  editableRequester: true,
                  fieldIndex: '2.0',
                  fieldLabel: 'plant',
                  fieldName: 'plant',
                  hasInformation: false,
                  keyField: true,
                  mandatory: true,
                  modifiedAt: '2026-02-25T10:10:40.910Z',
                  modifiedBy: 'multiple.demo@laidon.com',
                  sample: null,
                  sectionID: 'PLANTDATA',
                  shortFieldLabel: 'Plant',
                  showOnTableColumn: true,
                  sourceData: '{"additionalFilter":"","allowShowDescription":false,"display":["plantID"],"entity":"UIMDPlant","fields":["plantID","purchasingOrg","description"],"fixValues":[],"isOnPremise":false,"isUserInput":false,"key":"plantID","keyField":"","objectType":"Product","source":"","sourceType":"CUSTOMVIEW","tableName":"","targetSystem":""}',
                  sourceType: 'CUSTOMVIEW',
                  tempID: '2W_SM_MM01',
                  visibleApprover: true,
                  visibleRequestor: true,
                  isKeepValue: true,
                  additionalProps: {
                    visible: null,
                    path: 'fields/1/',
                    sourceRule: {
                      configRules: [
                        {
                          configType: 'FILTER',
                          configValue: 'plant',
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sliceFrom: null,
                          sliceLength: null,
                          sourceField: 'plant',
                          sourceSectionID: 'PLANTDATA',
                          targetField: 'mrpResponsible',
                          targetSectionID: 'MRP1',
                          tempID: '2W_SM_MM01',
                        },
                        {
                          configType: 'FILTER',
                          configValue: 'plant',
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          sliceFrom: null,
                          sliceLength: null,
                          sourceField: 'plant',
                          sourceSectionID: 'PLANTDATA',
                          targetField: 'storageLocation',
                          targetSectionID: 'STORAGELOCATION',
                          tempID: '2W_SM_MM01',
                        },
                      ],
                      derivationRules: [
                        {
                          createdAt: '2026-02-25T10:10:40.910Z',
                          createdBy: 'multiple.demo@laidon.com',
                          isEnable: true,
                          modifiedAt: '2026-02-25T10:10:40.910Z',
                          modifiedBy: 'multiple.demo@laidon.com',
                          ruleID: 'PRD_PRD_PLANT',
                          tempID: '2W_SM_MM01',
                          derivationRules: [
                            {
                              businessField: 'plant',
                              businessTable: 'ProductPlant',
                              configType: 'Source',
                              configValue: '0001',
                              createdAt: '2024-10-08T07:35:56.242Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: 'EQUAL',
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpType',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: 'ND',
                              createdAt: '2024-10-08T07:52:27.523Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'replacementPart',
                              businessTable: 'ProductPlant',
                              configType: 'Target',
                              configValue: 'A',
                              createdAt: '2024-10-08T08:05:51.935Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpResponsible',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: '0001-001',
                              createdAt: '2024-10-08T07:53:47.425Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpGroup',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: '0001-0000',
                              createdAt: '2024-10-08T08:18:23.785Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'mrpType',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: 'PD',
                              createdAt: '2024-10-08T08:17:26.594Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'lotSizingProcedure',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: 'PK',
                              createdAt: '2024-10-08T07:47:01.395Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'lotSizingProcedure',
                              businessTable: 'ProductPlantMRPArea',
                              configType: 'Target',
                              configValue: 'EX',
                              createdAt: '2024-10-08T08:19:16.017Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                            {
                              businessField: 'inHouseProductionTime',
                              businessTable: 'ProductSupplyPlanning',
                              configType: 'Target',
                              configValue: '5',
                              createdAt: '2024-10-08T07:45:27.389Z',
                              createdBy: 'multiple.demo@laidon.com',
                              isEnable: true,
                              modifiedAt: '2025-12-30T09:25:18.390Z',
                              modifiedBy: 'multiple.demo@laidon.com',
                              name: 'Plant',
                              operator: null,
                              ruleID: 'PRD_PRD_PLANT',
                            },
                          ],
                          options: {
                            singleSource: false,
                            repeatableSourceTargetLine: [0],
                          },
                        },
                      ],
                    },
                    isKeepValue: true,
                    selectedMDData: {
                      description: 'Plant 0003 (is-ht-sw)',
                      isActive: true,
                      plantID: '0003',
                      purchasingOrg: null,
                    },
                  },
                  value: '0003',
                  hiddenControlId: '__input31',
                  controlId: '__input30',
                  keyFieldValue: '0003',
                  valueState: 'None',
                  valueStateText: '',
                },
              ],
              canBeApproved: true,
            },
          ],
          additionalProps: {
            visible: null,
            path: 'values/0/sections/2/',
          },
        },
      ],
      fields: [],
    },
  ],
  additionalProps: {
    visible: null,
  },
}

// Usage
removeFields(originalData)
